### ISSUE TITLE
[BE] mockup API Server, API 설계

### ISSUE THREAD

**Issue by donggi-lee-bit** [ku-kim/todo-list#14]
## 기능 요청사항

- mock API Server  생성

## 요청 세부사항

- postman 을 이용해 mock Server 를 생성하여 mock API 를 생성해주세요.

**Comment by ku-kim** [comment]
[wiki : Mock API Server 도입과 이유](https://github.com/ku-kim/todo-list/wiki/Mockup-API-Server)

[구현한 Mockup API 문서](https://documenter.getpostman.com/view/20358957/UVyuRuZa)

요청 서버 {{uri}} : https://f278a12c-c825-466b-aa01-65337bbdf28a.mock.pstmn.io

| 요청 | 기능 | 상태코드 |
| --- | --- | --- |
| `GET {{uri}}/api/todos` | 모든 Todo를 List 형태로 보낸다. | 200 |
| `GET {{uri}}/api/todos/{id}` | 해당 id의 Todo 보낸다. | 200 |
| `POST {{uri}}/api/todos` | 새로운 Todo를 생성한다. | 201 |
| `DLELTE {{uri}}/api/todos/{id}` | 해당 id의 Todo를 삭제한다. | 204 |
| `PATCH {{uri}}/api/todos/{id}` | 해당 id의 Todo를 업데이트한다. | 200 |
|  |  |  |
| `GET {{uri}}/api/histories` | 모든 히스토리를 보내준다. | 200 |
