### ISSUE TITLE
[Android] BE 목업서버 Url형식 변경요청

### ISSUE THREAD

**Issue by shncder** [ku-kim/todo-list#27]
## 기능 요청사항

목업서버 Url형식 변경요청

## 요청 세부사항

ex) {{url}}/api/todos  >>> url/api/{todos}

아래 사진을 참조하면 { }안에 있는 부분은 변수를 주는 부분인데

{url}로 표현해놓으면 url주소에 변수가 들어간다는 같은 혼란을 줌

todos부분은 histories와 변경사항이 있어 변수처리가 필요하다고 생각됨

## 레퍼런스

![4](https://user-images.githubusercontent.com/91953080/162022483-e73ac325-3f59-483b-bfb6-1576465bca85.png)

**Comment by ku-kim** [comment]
가독성을 위해 API 설계 테이블 표에서 {{api}} 변경하였습니다.
하지만 mockup 서버에서 {{uri}}를 제거하면 예시 데이터를 보여줄 수 없어서 API 문서에는 반영하지 못했네요. :( 

| 요청 | 기능 | 상태코드 |
| --- | --- | --- |
| `GET /api/todos` | 모든 Todo를 List 형태로 보낸다. | 200 |
| `GET /api/todos/{id}` | 해당 id의 Todo 보낸다. | 200 |
| `POST /api/todos` | 새로운 Todo를 생성한다. | 201 |
| `DLELTE /api/todos/{id}` | 해당 id의 Todo를 삭제한다. | 204 |
| `PATCH /api/todos/{id}` | 해당 id의 Todo를 업데이트한다. | 200 |
|  |  |  |
| `GET /api/histories` | 모든 히스토리를 보내준다. | 200 |
